package com.crtyiot.scan.data.network

// Generated by Copilot
// retrofit get mat info
// base url setting in AppContainer

import com.crtyiot.ept.data.model.Material
import retrofit2.http.GET
import retrofit2.http.Path

interface MaterialApiService {
    @GET("materials")
    suspend fun getAllMaterials(): List<Material>

    @GET("materials/{id}")
    suspend fun getMaterialById(@Path("id") id: Int): Material
}